from channel_url import *
import pandas as pd
video_url = ['https://www.youtube.com/c/GOT7/videos','https://www.youtube.com/c/%EA%B0%95%EB%8B%A4%EB%8B%88%EC%97%98KANGDANIEL/videos','https://www.youtube.com/c/GoldenChild/videos','https://www.youtube.com/c/OFFICIALKIMSEJEONG0828/videos','https://www.youtube.com/channel/UC1RjCqJ8nlQq-kx7mXYhPWg/videos','https://www.youtube.com/user/pledisnuest/videos','https://www.youtube.com/c/THEBOYZofficial/videos','https://www.youtube.com/c/DAY6Official/videos','https://www.youtube.com/c/redvelvet/videos','https://www.youtube.com/c/MAMAMOO_OFFICIAL/videos','https://www.youtube.com/c/monstax/videos','https://www.youtube.com/c/PARKJIHOONOfficial/videos','https://www.youtube.com/channel/UCx_kYu6Wp1yxZP_KtrW52EQ/videos','https://www.youtube.com/user/7seasons2013/videos','https://www.youtube.com/c/BLACKPINKOFFICIAL/videos','https://www.youtube.com/c/officialbtob/videos','https://www.youtube.com/c/VICTON1109/videos','https://www.youtube.com/user/SHINee/videos','https://www.youtube.com/user/pledis17/videos','https://www.youtube.com/user/GIRLSGENERATION/videos','https://www.youtube.com/c/STAYC/videos','https://www.youtube.com/user/SUPERJUNIOR/videos','https://www.youtube.com/c/StrayKids/videos','https://www.youtube.com/c/gidleofficial/videos','https://www.youtube.com/c/offclASTRO/videos','https://www.youtube.com/c/dlwlrma/videos','https://www.youtube.com/c/officialIZONE/videos','https://www.youtube.com/c/officialAKMU/videos','https://www.youtube.com/c/SF9official/videos','https://www.youtube.com/c/aespa/videos','https://www.youtube.com/c/AB6IX/videos','https://www.youtube.com/c/ATEEZofficial/videos','https://www.youtube.com/c/officialapink/videos','https://www.youtube.com/c/weareoneEXO/videos','https://www.youtube.com/c/nctsmtown/videos','https://www.youtube.com/c/nflyingofficial/videos','https://www.youtube.com/c/ENHYPENOFFICIAL/videos','https://www.youtube.com/c/gfrdofficial/videos','https://www.youtube.com/c/OHMYGIRL/videos','https://www.youtube.com/c/ONF_OFFICIAL/videos','https://www.youtube.com/c/ONEUS/videos','https://www.youtube.com/c/WONHOofficial/videos','https://www.youtube.com/c/OfficialYGWINNER/videos','https://www.youtube.com/c/WEiOfficial/videos','https://www.youtube.com/c/Weeekly/videos','https://www.youtube.com/c/loonatheworld/videos','https://www.youtube.com/c/ITZY/videos','https://www.youtube.com/c/jeongsewoon/videos','https://www.youtube.com/c/CRAVITYstarship/videos','https://www.youtube.com/c/TXT_bighit/videos','https://www.youtube.com/user/2pm/videos','https://www.youtube.com/c/OfficialTreasure/videos','https://www.youtube.com/c/TWICE/videos','https://www.youtube.com/c/officialpentagon/videos','https://www.youtube.com/c/PURPLEKISS/videos','https://www.youtube.com/c/Officialfromis9/videos','https://www.youtube.com/c/%ED%95%98%EC%84%B1%EC%9A%B4HASUNGWOON/videos','https://www.youtube.com/c/OFFICIALHIGHLIGHT/videos']


df = pd.read_csv('C:/Users/User/Desktop/workspace/mulcam_army/blip_artists_list.csv', index_col=0)  # 여기만 바꿔주시면 됩니다!
df['video_url']=video_url

for i in df.video_url:
    get_video_title(i)
